### ISSUE TITLE
Plugins not start 

### ISSUE THREAD

**Issue by ikicakus** [starxg/terminus-sync-config#14]
![image](https://user-images.githubusercontent.com/33986638/123930375-e3dcaf00-d9b9-11eb-8b68-7abdf8ea8b5c.png)

Terminus could not start with your plugins, so all third party plugins have been disabled in this session. The error was:
Error: Can't resolve all parameters for v: ([object Object], [object Object], ?, [object Object]).

**Comment by starxg** [comment]
update to [terminus140+](https://github.com/Eugeny/terminus/releases)

look at these issues ：
[https://github.com/Eugeny/terminus/issues/4013](https://github.com/Eugeny/terminus/issues/4013)
#13 
#12
