### ISSUE TITLE
For gitlab deployed by your own server, can you add the function of customizing the gitlab server address

### ISSUE THREAD

**Issue by yinxiulong** [starxg/terminus-sync-config#20]
For gitlab deployed by your own server, can you add the function of customizing the gitlab server address

**Comment by rolser-victor** [comment]
This actually would be helpful for us too. We have a self-hosted gitlab service.

**Comment by yinxiulong** [comment]
Many people should use it. Now most companies have their own gitlab

**Comment by SingHar** [comment]
I would love that feature, we also use self-hosted Gitlab.
