### ISSUE TITLE
配置同步包括哪些内容,可以介绍一下吗

### ISSUE THREAD

**Issue by noday** [starxg/terminus-sync-config#23]
可以介绍一下吗

**Comment by starxg** [comment]
会同步 `config.yaml` 文件

![{13BC6EFC-758E-5602-E109-AAFEC8EC3796}](https://user-images.githubusercontent.com/34997494/144531624-e9a76314-e585-4b2a-a24d-df74073511d4.jpg)

**Comment by hyy34** [comment]
> 会同步 `config.yaml` 文件
> 
> ![{13BC6EFC-758E-5602-E109-AAFEC8EC3796}](https://user-images.githubusercontent.com/34997494/144531624-e9a76314-e585-4b2a-a24d-df74073511d4.jpg)
请问，我选择的是gitee，那么这个文件上传到什么位置了？我在gitee在哪里可以查看到？

**Comment by starxg** [comment]
> > 会同步 `config.yaml` 文件
> 
> > 
> 
> > ![{13BC6EFC-758E-5602-E109-AAFEC8EC3796}](https://user-images.githubusercontent.com/34997494/144531624-e9a76314-e585-4b2a-a24d-df74073511d4.jpg)
> 
> 请问，我选择的是gitee，那么这个文件上传到什么位置了？我在gitee在哪里可以查看到？
> 
> 

gist gitee
