### ISSUE TITLE
Plugin not loaded

### ISSUE THREAD

**Issue by Gadlae** [starxg/terminus-sync-config#4]
### Description
Since the Update to Version 1.0.2, the Plugin ist not longer loaded. So far there is no Error Message and it is also not displayed in the left Sidebar.
The Version 1.0.1 works fine.

![image](https://user-images.githubusercontent.com/36635810/114217210-2b7a0e80-9968-11eb-9161-2b1740427002.png)

### Environment
- Terminus 1.0.135
- Terminus sync-config 1.0.2
- Windows 10 20H2 / Windows 10 2004

Thanks for fixing it

**Comment by Gadlae** [comment]
Yes i have already tried. I also tried it on a new WIN10.

**Comment by starxg** [comment]
Thank you for your feedback. Please use version [1.0.3](https://www.npmjs.com/package/terminus-sync-config)
